GET http://localhost:8000/

###

GET http://localhost:8000/todos

###

GET http://localhost:8000/todos/2
content-type: application/json

###

POST http://localhost:8000/todos/
Content-Type: application/json

{
    "title": "Petting Deno"
}

###

PUT http://localhost:8000/todos/1
content-type: application/json

###

DELETE http://localhost:8000/todos/5